[package]
name = "lap-sim-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.12"
csv = "1.3.0"
serde = "1.0.197"
serde_derive = "1.0.197"
nalgebra = "0.32.4"